---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short

- openmeteo:
    label: 杭州 # optional
    latitude: 30.28
    longitude: 120.15
    timezone: Asia/Shanghai # optional
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1

- glances:
    url: http://127.0.0.1:61208
#    username: user # optional if auth enabled in Glances
#    password: pass # optional if auth enabled in Glances
    version: 4 # required only if running glances v4 or higher, defaults to 3
    cpu: true # optional, enabled by default, disable by setting to false
    mem: true # optional, enabled by default, disable by setting to false
#    cputemp: true # disabled by default
    uptime: true # disabled by default
    disk: f:\ # disabled by default, use mount point of disk(s) in glances. Can also be a list (see below)
    diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
    expanded: true # show the expanded view
#    label: MyMachine # optional
